### ISSUE TITLE
Use ES6 syntax - passtough harmony setting to react-tools

### ISSUE THREAD

**Issue by kfiil** [tillarnold/grunt-jsxhint#22]
Hi,

Great grunt task! Would it be possible sometime to add the option to pass options to react-tools? I need to set harmony:true :)

**Comment by kfiil** [comment]
Hmm seems like the harmony:true setting are not doing the trick regarding ES6

**Comment by Munter** [comment]
react-tools do not have a full ES6 implementation, so you won't be able to use all of the new stuff. I really wanted to start using `const` and `let`, but couldn't. Yet...

**Comment by kfiil** [comment]
But it will let something go, I have just have success with the es6module flag:
compiled = react.transform(code,  {es6module: true});
Could be nice to be able to pass options to react tools :)

**Comment by Munter** [comment]
I'm using a lot of es6 functions and haven't set up anything specific for grunt-jsxhint. It just works out of the box. Are you setting `"esnext": true` in your jshint config?

**Comment by kfiil** [comment]
I have `"esnext": true` but get this error:
`Illegal import declaration Use --force to continue.`
if i do not have `{es6module: true}`

**Comment by tillarnold** [comment]
I guess this is not a problem any more since we now use babel.
