### ISSUE TITLE
List `react-tools` as a real dependency (not devDependencies)

### ISSUE THREAD

**Issue by rxaviers** [tillarnold/grunt-jsxhint#25]
It seems like `react-tools` is a real dependency, not a devDependency.

**Comment by djmccormick** [comment]
+1

**Comment by mathieumg** [comment]
`react-tools` is getting deprecated, so you might want to consider switching to Babel at this point. :stuck_out_tongue:

**Comment by tillarnold** [comment]
We use babel now.
