### ISSUE TITLE
Babel option

### ISSUE THREAD

**Issue by Atsman** [tillarnold/grunt-jsxhint#26]
Hi, 

I want to use your plugin, but i faced a problem, that there are no ability to use babel transformation instead of react tools.

Are you plan to provide this ability?

**Comment by iamkoch** [comment]
There's 1 line that does the actual transform:

    compiled = react.transform(code);

Plus some other setup to ensure that the above line doesn't fail.

The transformer could be passed in and then instantiated accordingly. 

Have you considered forking and adding this yourself?

**Comment by underbyte** [comment]
Babel should be a requirement because the react team is deprecating the react-tools. [Read more here](https://facebook.github.io/react/blog/2015/06/12/deprecating-jstransform-and-react-tools.html)

**Comment by iamkoch** [comment]
Have you considered adding the support yourself?

Maybe something in the options like 

`transformer: 'babel'` 

and 

`compiled = props.transformer == 'babel' ? babel.compile(code) : react.transform(code);` 

would be sufficient?

**Comment by tparnell8** [comment]
BTW #28

**Comment by tillarnold** [comment]
closed by #28
